---
apiVersion: v1
kind: Service
metadata:
  name: abctech-service
  labels:
   app: abctech-app
spec:
  type: NodePort
  ports:
   - targetPort: 9090
     port: 9090
     nodePort: 30010
  selector:
    app: abctech-app
...
